# Generated by Django 6.0.6 on 2026-06-06 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='IntentoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('finalizado', 'Finalizado')], default='en_curso', max_length=12)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'intento de evaluacion',
                'verbose_name_plural': 'intentos de evaluacion',
            },
        ),
        migrations.CreateModel(
            name='RespuestaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False)),
                ('fecha_respuesta', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'respuesta de alumno',
                'verbose_name_plural': 'respuestas de alumno',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('numero_preguntas', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], default='programada', max_length=12)),
                ('finalizada_anticipadamente', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(related_name='evaluaciones', to='catalogo.categoria')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='catalogo.materia')),
                ('preguntas', models.ManyToManyField(blank=True, related_name='evaluaciones', to='catalogo.pregunta')),
            ],
            options={
                'verbose_name': 'evaluacion',
                'verbose_name_plural': 'evaluaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
