# Generated by Django 6.0.6 on 2026-06-06 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='grupos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='catalogo.institucion'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='evaluaciones.grupo'),
        ),
        migrations.AddField(
            model_name='intentoevaluacion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intentoevaluacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='evaluaciones.evaluacion'),
        ),
        migrations.AddField(
            model_name='respuestaalumno',
            name='intento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.intentoevaluacion'),
        ),
        migrations.AddField(
            model_name='respuestaalumno',
            name='opcion_seleccionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='catalogo.opcionrespuesta'),
        ),
        migrations.AddField(
            model_name='respuestaalumno',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='catalogo.pregunta'),
        ),
        migrations.AlterUniqueTogether(
            name='intentoevaluacion',
            unique_together={('evaluacion', 'alumno')},
        ),
        migrations.AlterUniqueTogether(
            name='respuestaalumno',
            unique_together={('intento', 'pregunta')},
        ),
    ]
