# Generated by Django 6.0.6 on 2026-06-06 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='grupos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
