# Generated by Django 6.0.6 on 2026-09-05 06:01

import django.db.models.deletion
from django.db import migrations, models


def traspasar_categorias(apps, schema_editor):
    """Convierte las categorias que ya estaban en renglones con su numero.

    Las evaluaciones anteriores guardaban un total y una lista de categorias,
    sin decir cuantas preguntas tocaban a cada una. Se reparte el total en
    partes iguales y el sobrante se le suma a la primera.
    """
    Evaluacion = apps.get_model('evaluaciones', 'Evaluacion')
    CategoriaEvaluacion = apps.get_model('evaluaciones', 'CategoriaEvaluacion')

    for evaluacion in Evaluacion.objects.all():
        categorias = list(evaluacion.categorias.all())
        if not categorias:
            continue

        por_categoria, sobrante = divmod(evaluacion.numero_preguntas, len(categorias))
        for posicion, categoria in enumerate(categorias):
            numero = por_categoria + (sobrante if posicion == 0 else 0)
            CategoriaEvaluacion.objects.create(
                evaluacion=evaluacion,
                categoria=categoria,
                numero_preguntas=numero,
            )


def deshacer_traspaso(apps, schema_editor):
    """Regresa los renglones a la relacion simple de categorias."""
    Evaluacion = apps.get_model('evaluaciones', 'Evaluacion')
    for evaluacion in Evaluacion.objects.all():
        evaluacion.categorias.set(
            [fila.categoria for fila in evaluacion.categorias_elegidas.all()]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
        ('evaluaciones', '0003_grupo_profesores'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_preguntas', models.PositiveSmallIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='catalogo.categoria')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_elegidas', to='evaluaciones.evaluacion')),
            ],
            options={
                'verbose_name': 'categoria de la evaluacion',
                'verbose_name_plural': 'categorias de la evaluacion',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'categoria'), name='categoria_unica_por_evaluacion')],
            },
        ),
        migrations.RunPython(traspasar_categorias, deshacer_traspaso),
        migrations.RemoveField(
            model_name='evaluacion',
            name='categorias',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='numero_preguntas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
