# Generated by Django 6.0.6 on 2026-09-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_categorias_con_numero_de_preguntas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaevaluacion',
            options={'ordering': ['id'], 'verbose_name': 'categoría de la evaluación', 'verbose_name_plural': 'categorías de la evaluación'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'evaluación', 'verbose_name_plural': 'evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='intentoevaluacion',
            options={'verbose_name': 'intento de evaluación', 'verbose_name_plural': 'intentos de evaluación'},
        ),
    ]
