# Generated by Django 6.0.6 on 2026-09-20 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_categoria_options_alter_materia_options'),
        ('evaluaciones', '0005_nombres_con_acentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # No se puede convertir un M2M normal en uno con through directamente:
        # primero se quita el viejo (se pierden los vinculos profesor-grupo, que
        # se recrean con datos_demo/datos_iniciales), luego se crea la tabla
        # intermedia con la asignatura y por ultimo se agrega el M2M nuevo.
        migrations.RemoveField(
            model_name='grupo',
            name='profesores',
        ),
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='catalogo.categoria')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='evaluaciones.grupo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asignación docente',
                'verbose_name_plural': 'asignaciones docentes',
                'ordering': ['grupo', 'profesor', 'categoria'],
                'unique_together': {('grupo', 'profesor', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='grupos_asignados', through='evaluaciones.AsignacionDocente', to=settings.AUTH_USER_MODEL),
        ),
    ]
