# Generated by Django 6.0.6 on 2026-09-20 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_categoria_materia_alter_pregunta_categoria_and_more'),
        ('evaluaciones', '0006_asignaciondocente_alter_grupo_profesores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaevaluacion',
            options={'ordering': ['id'], 'verbose_name': 'asignatura de la evaluación', 'verbose_name_plural': 'asignaturas de la evaluación'},
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='catalogo.categoria', verbose_name='asignatura'),
        ),
        migrations.AlterField(
            model_name='categoriaevaluacion',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='catalogo.categoria', verbose_name='asignatura'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='catalogo.materia', verbose_name='disciplina'),
        ),
    ]
