# Generated by Django 6.0.6 on 2026-09-21 23:16

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0007_alter_categoriaevaluacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': [django.db.models.functions.comparison.Collate(models.F('nombre'), 'es_sin_acentos')], 'verbose_name': 'grupo', 'verbose_name_plural': 'grupos'},
        ),
    ]
