# Generated by Django 6.0.6 on 2026-09-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['materia', 'nombre'], 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'verbose_name': 'institución', 'verbose_name_plural': 'instituciones'},
        ),
        migrations.AlterModelOptions(
            name='opcionrespuesta',
            options={'verbose_name': 'opción de respuesta', 'verbose_name_plural': 'opciones de respuesta'},
        ),
    ]
