# Generated by Django 6.0.6 on 2026-09-05 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def marcar_preguntas_existentes(apps, schema_editor):
    """Las preguntas que ya existian las capturo una persona y ya estaban en uso.

    Sin esto se quedarian en borrador, que es el valor por omision, y el
    sistema se quedaria sin banco de preguntas para armar evaluaciones.
    """
    Pregunta = apps.get_model('catalogo', 'Pregunta')
    Pregunta.objects.update(origen='manual', estado='validada')


def deshacer_marcado(apps, schema_editor):
    """No hay nada que revertir: los campos desaparecen con la migracion."""


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_nombres_con_acentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('validada', 'Validada'), ('descartada', 'Descartada')], default='borrador', max_length=12),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='motivo_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='origen',
            field=models.CharField(choices=[('manual', 'Capturada por el profesor'), ('ia', 'Generada con inteligencia artificial')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='procedimiento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='verificada_simbolicamente',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SolicitudGeneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.PositiveSmallIntegerField()),
                ('cantidad_recibida', models.PositiveSmallIntegerField(default=0)),
                ('cantidad_aprobada', models.PositiveSmallIntegerField(default=0)),
                ('modelo', models.CharField(blank=True, max_length=60)),
                ('tokens_entrada', models.PositiveIntegerField(default=0)),
                ('tokens_salida', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('exitosa', models.BooleanField(default=False)),
                ('detalle_error', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='catalogo.categoria')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='catalogo.materia')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='catalogo.nivel')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_generacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de generación',
                'verbose_name_plural': 'solicitudes de generación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='catalogo.solicitudgeneracion'),
        ),
        migrations.RunPython(marcar_preguntas_existentes, deshacer_marcado),
    ]
