# Generated by Django 6.0.6 on 2026-09-06 01:17

from django.db import migrations, models


def marcar_materias_cuantitativas(apps, schema_editor):
    """Marca como cuantitativas las materias que ya existen y lo son.

    Se hace por nombre porque son las dos del catalogo actual. Las materias
    que se den de alta despues las marca el administrador desde el panel.
    """
    Materia = apps.get_model('catalogo', 'Materia')
    Materia.objects.filter(
        nombre__in=['Matemáticas', 'Matematicas', 'Física', 'Fisica', 'Química', 'Quimica']
    ).update(es_cuantitativa=True)


def desmarcar(apps, schema_editor):
    """Nada que revertir: el campo desaparece con la migracion."""


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_preguntas_generadas_con_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='es_cuantitativa',
            field=models.BooleanField(default=False),
        ),
            migrations.RunPython(marcar_materias_cuantitativas, desmarcar),
    ]
