# Generated by Django 6.0.6 on 2026-09-06 02:24

from django.db import migrations, models


def trasladar_el_resultado(apps, schema_editor):
    """Pasa el booleano exitosa al campo de estado antes de que desaparezca.

    Sin este paso las solicitudes que ya existen se quedarian en "en proceso",
    que es el valor por omision, y la pantalla de espera las daria por
    inconclusas para siempre.
    """
    Solicitud = apps.get_model('catalogo', 'SolicitudGeneracion')
    Solicitud.objects.filter(exitosa=True).update(estado='exitosa')
    Solicitud.objects.filter(exitosa=False).update(estado='fallida')


def devolver_el_resultado(apps, schema_editor):
    """El camino de regreso, por si hay que revertir la migracion."""
    Solicitud = apps.get_model('catalogo', 'SolicitudGeneracion')
    Solicitud.objects.filter(estado='exitosa').update(exitosa=True)
    Solicitud.objects.exclude(estado='exitosa').update(exitosa=False)


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_materia_cuantitativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudgeneracion',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('exitosa', 'Exitosa'), ('fallida', 'Fallida')], default='en_proceso', max_length=12),
        ),
        migrations.AddField(
            model_name='solicitudgeneracion',
            name='mensaje_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitudgeneracion',
            name='tipo_error',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(trasladar_el_resultado, devolver_el_resultado),
        migrations.RemoveField(
            model_name='solicitudgeneracion',
            name='exitosa',
        ),
    ]
