# Generated by Django 6.0.6 on 2026-09-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_estado_de_la_solicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['materia', 'nombre'], 'verbose_name': 'asignatura', 'verbose_name_plural': 'asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre'], 'verbose_name': 'disciplina', 'verbose_name_plural': 'disciplinas'},
        ),
    ]
