# Generated by Django 6.0.6 on 2026-09-20 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_categoria_options_alter_materia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='catalogo.materia', verbose_name='disciplina'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='catalogo.categoria', verbose_name='asignatura'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='catalogo.materia', verbose_name='disciplina'),
        ),
        migrations.AlterField(
            model_name='solicitudgeneracion',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='catalogo.categoria', verbose_name='asignatura'),
        ),
        migrations.AlterField(
            model_name='solicitudgeneracion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='catalogo.materia', verbose_name='disciplina'),
        ),
    ]
