# Generated by Django 6.0.6 on 2026-09-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_categoria_materia_alter_pregunta_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['materia__nombre', 'nombre'], 'verbose_name': 'asignatura', 'verbose_name_plural': 'asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['nombre'], 'verbose_name': 'institución', 'verbose_name_plural': 'instituciones'},
        ),
    ]
