# Generated by Django 6.0.6 on 2026-09-21 23:16

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_categoria_options_alter_institucion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': [django.db.models.functions.comparison.Collate(models.F('materia__nombre'), 'es_sin_acentos'), django.db.models.functions.comparison.Collate(models.F('nombre'), 'es_sin_acentos')], 'verbose_name': 'asignatura', 'verbose_name_plural': 'asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': [django.db.models.functions.comparison.Collate(models.F('nombre'), 'es_sin_acentos')], 'verbose_name': 'institución', 'verbose_name_plural': 'instituciones'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': [django.db.models.functions.comparison.Collate(models.F('nombre'), 'es_sin_acentos')], 'verbose_name': 'disciplina', 'verbose_name_plural': 'disciplinas'},
        ),
    ]
