# Generated by Django 6.0.6 on 2026-09-22 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_alter_categoria_options_alter_institucion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripciones_nivel', to='catalogo.categoria', verbose_name='asignatura')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripciones_categoria', to='catalogo.nivel')),
            ],
            options={
                'verbose_name': 'tipo de preguntas por nivel',
                'verbose_name_plural': 'tipos de preguntas por nivel',
                'ordering': ['categoria', 'nivel__numero'],
                'unique_together': {('categoria', 'nivel')},
            },
        ),
    ]
