# Generated by Django 6.0.6 on 2026-09-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_reducir_a_tres_niveles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
    ]
