# Generated by Django 6.0.6 on 2026-09-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_remove_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='expresion',
            field=models.CharField(blank=True, max_length=300, verbose_name='expresión'),
        ),
    ]
