# Generated by Django 6.0.6 on 2026-09-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_pregunta_modificada_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
