# Generated by Django 6.0.6 on 2026-09-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico'),
        ),
    ]
