# Generated by Django 6.0.6 on 2026-09-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_persona_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('alumno', 'Alumno'), ('profesor', 'Profesor')], default='alumno', max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('otro', 'Otro')], max_length=10),
        ),
    ]
