# Generated by Django 6.0.6 on 2026-09-21 23:16

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_persona_rol_alter_persona_sexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': [django.db.models.functions.comparison.Collate(models.F('apellido'), 'es_sin_acentos'), django.db.models.functions.comparison.Collate(models.F('nombre'), 'es_sin_acentos')], 'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
    ]
